// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2iaODyRgyPLjzK44O6OvmonSz_BRT-zU',
    appId: '1:1020248010717:web:efd5a8f773230076d49034',
    messagingSenderId: '1020248010717',
    projectId: 'gun-store-3a384',
    authDomain: 'gun-store-3a384.firebaseapp.com',
    storageBucket: 'gun-store-3a384.appspot.com',
    measurementId: 'G-NCMKS9VBQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkvYmhjvuXmpG-YMpucNDYnDEdHskcorY',
    appId: '1:1020248010717:android:83cf8316350052ddd49034',
    messagingSenderId: '1020248010717',
    projectId: 'gun-store-3a384',
    storageBucket: 'gun-store-3a384.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuahdBv39FIZBFB52ZMMTbGhJRy1q7ZBQ',
    appId: '1:1020248010717:ios:bd0267cd0447a697d49034',
    messagingSenderId: '1020248010717',
    projectId: 'gun-store-3a384',
    storageBucket: 'gun-store-3a384.appspot.com',
    iosBundleId: 'com.example.ggo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuahdBv39FIZBFB52ZMMTbGhJRy1q7ZBQ',
    appId: '1:1020248010717:ios:bd0267cd0447a697d49034',
    messagingSenderId: '1020248010717',
    projectId: 'gun-store-3a384',
    storageBucket: 'gun-store-3a384.appspot.com',
    iosBundleId: 'com.example.ggo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2iaODyRgyPLjzK44O6OvmonSz_BRT-zU',
    appId: '1:1020248010717:web:71965664b6ae61a0d49034',
    messagingSenderId: '1020248010717',
    projectId: 'gun-store-3a384',
    authDomain: 'gun-store-3a384.firebaseapp.com',
    storageBucket: 'gun-store-3a384.appspot.com',
    measurementId: 'G-40QGH8YHNF',
  );

}